"""Add email verification fields to users table

Revision ID: c838208da943
Revises: 00772281d8b0
Create Date: 2026-01-24 00:04:58.999234

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c838208da943"
down_revision: str | None = "00772281d8b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add verification_token first (nullable)
    op.add_column(
        "users", sa.Column("verification_token", sa.String(length=255), nullable=True)
    )

    # Add email_verified as nullable first
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=True))

    # Update existing users to have email_verified=False
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")

    # Now make email_verified NOT NULL
    op.alter_column("users", "email_verified", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "verification_token")
    op.drop_column("users", "email_verified")
    # ### end Alembic commands ###
